### ISSUE TITLE
Bcdatabase files do not work properly with completely empty entries

### ISSUE THREAD

**Issue by rsutphin** [northwestern-fsm/bcdatabase#13]
A Bcdatabase file like the following could work, but doesn't currently:

``` yaml
defaults:
  host: localhost
  adapter: postgresql
  username: me
  password: mydevpass
personnel:
warehouse:
```

In this case, the expectation is that there are two configurations — `:personnel` and `:warehouse` — that differ only in the `database` key. The `database` key should be defaulted from the entry name, but in this case it won't be. Instead, the entry is skipped entirely.

A  workaround is to set the entry value to a YAML hash literal like so:

``` yaml
personnel: {}
```
